DROP SCHEMA IF EXISTS checkout_schema CASCADE;
CREATE SCHEMA checkout_schema;

SET search_path TO checkout_schema;

CREATE TABLE IF NOT EXISTS orders (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status     VARCHAR(32) NOT NULL,
  total      DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  item_id    BIGINT NOT NULL,
  name       VARCHAR(64) NOT NULL,
  quantity   INTEGER NOT NULL,
  unit_price DOUBLE PRECISION NOT NULL,
  line_total DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);